### ISSUE TITLE
Size of cover

### ISSUE THREAD

**Issue by jvanoost** [raywo/MMM-NowPlayingOnSpotify#13]
Hi,
Thanks for your module. Great job
On my mirror the cover is very big
Is that possible to reduce the width ?
Thanks
Jerome

**Comment by mrdago** [comment]
Jerome, I've edited the style file (css/styles.css) and reduced the cover size to 70%.
```
...
.NPOS_albumCover {
  width: 70%;
}
...
```

**Comment by jvanoost** [comment]
thanks !
I'll test tonight!
