### ISSUE TITLE
Rapberry Pi 3 running hot

### ISSUE THREAD

**Issue by drftg** [raywo/MMM-NowPlayingOnSpotify#15]
Running just this module and nothing else, the cpu utilization on my RPi3 is over 70%. A temperature warning pops up after a while in the upper right corner.
Any ideas on how to reduce the cpu load?

**Comment by raywo** [comment]
The module updates its status every second. Although that shouldn’t be a problem, you can change that behaviour. Try to set `updatesEvery` to a higher value. Maybe five. If then experiencing the same problems then it has another reason. 
Maybe you should disable all module an see what happens then.

**Comment by drftg** [comment]
Sorry, turned out to be an issue with an issue with electron
`npm install electron@1.4.15` solved it
