### ISSUE TITLE
Title and cover art still display when music is paused/spotify is closed on laptop & phone

### ISSUE THREAD

**Issue by AndrewMcClelland** [raywo/MMM-NowPlayingOnSpotify#17]
First of all, great module! Works fantastic and was so easy to setup.

Only issue I'm having is that the module still displays (cover art + title) when my Spotify is paused. Is this supposed to happen? How do I get it to dissappear if my Spotify is paused?

Thanks!

**Comment by raywo** [comment]
The Spotify API can’t decide whether you paused your playback or actually stopped your playback. That’s why the cover art and title are still displayed although you paused playback. 
If you actually want the display to disappear you need to quit Spotify. That is the only way for the API to really know that your playback is stopped.

**Comment by szymansk** [comment]
you could add the option 'displayOnPause'

But you also need to change the line 55 in `node_helper.js`from

'''
 isPlaying: songInfo.isPlaying,
'''

to

'''
        isPlaying: songInfo.is_playing,
'''

to be able to see if a song is paused or not.

**Comment by kisbosze** [comment]
Hy,

everything works fine if I don't connect to raspberry. The song information disappears from the mirror when I quit.

But when I connect to raspberry and pause the spotify on my phone and quit, the song data stays on the display and doesn't return to the logo.

Please help me :)
