### ISSUE TITLE
must have Spotify premium account to use it?

### ISSUE THREAD

**Issue by sagtool** [raywo/MMM-NowPlayingOnSpotify#19]
i followed all the steps corectly (create dev account on spotify, and also go secret id)
but no logo or cover appear,
i must have premium account or free acount is ok ?

**Comment by raywo** [comment]
If you followed all the steps everything should work.
Did you restart your MagicMirror?

**Comment by sagtool** [comment]
yes, its already restarted

2018-05-07 23:59 GMT+03:00 Ray Wojciechowski <notifications@github.com>:

**Comment by aaronmaynard** [comment]
@sagtool You do not need to have a prem account.  If you are only experiencing issues with the cover showing, it could be the `showCoverArt: "false",`, although this should be automatically set to true.  Try modifying this variable.
