### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by seelyowen** [raywo/MMM-NowPlayingOnSpotify#24]
After I type in my Client ID and Client Secret and click "Authorize My App!" it will show an error saying INVALID_CLIENT: Invalid redirect URI.

**Comment by pjamourik** [comment]
You should go to your Spotify developer dashboard and go to "EDIT SETTINGS" in the app that you created. 

Add the following URL to the Redirect URI's:

http://localhost:8888/callback
