### ISSUE TITLE
mine wont appear

### ISSUE THREAD

**Issue by ulv23** [raywo/MMM-NowPlayingOnSpotify#25]
i've already finished all the things to do and already got tokens,etc after I updated on config js then nothing appear. how can I solve the problem? thanks

**Comment by Rowcii** [comment]
Same problem here.. Just commenting so I get notified if someone knows the solution :/

**Comment by ChristianEreira** [comment]
Same problem here as well. The module is not even showing up on the remote.

**Comment by trevortreachery** [comment]
Same problem here. Everything seems configured correctly, no script errors. Just doesn't show up.

**Comment by daymonschultz** [comment]
Had the same issue. Noticed after installing it did not install into the Modules folder within the Magic Mirror. 

Go to Magic Mirror > Modules. Right click on Modules and open a terminal. Follow the steps from there.

**Comment by dombue** [comment]
Same Problem here as well….

**Comment by dombue** [comment]
Cool i could solve it :)

In my case, the Folder "MMM-NowPlayingOnSpotify" was at the wrong Location. If you have the same Problem just move it to the Folder MagicMirror/modules

After i have done that, it works fine :) Hope your having all the same Problem :)

**Comment by trevortreachery** [comment]
@dombue easy fix to my issue, worked perfectly after. Thank you!

**Comment by ChristianEreira** [comment]
Thanks, the fix works, can't believe I didn't notice that. Might want to add "cd MagicMirror/Modules" to the instructions before closing the issue.
