### ISSUE TITLE
Not working, stuck on load

### ISSUE THREAD

**Issue by PierreGode** [raywo/MMM-NowPlayingOnSpotify#59]
Hi have been trying to get this to work for 2 days now. 
I am getting API requests in the Spotify dashboard. 
But nothing happens on the mirror. I have notice that if I restart pm2 while playing music the Mirror starts with the return domBuilder.getInitDom(this.translate('LOADING')); and stays there.
but as soon I stop the music It returns to the logo but nothing happens when I play music again.
I also did a fork to test updating app.js "Buffer() is depricated" 
'Authorization': 'Basic ' + (new Buffer(client_id + ':' + client_secret).toString('base64'))    to     'Authorization': 'Basic ' + (new Buffer.from(client_id + ':' + client_secret).toString('base64'))
but I have the exact same issue now. I don belive it to be a token issue due to the fact i am getting requests in the dashboard. 
I am not really sure what to look for...
Best regards Pierre

**Comment by lorettet** [comment]
It took me few hours to debug this (never done any node before), but I finally managed to make it work!
There is an error in the display, you can easily find it with `npm run start dev`. The error is in `core/NPOS_DOMBuilder.js`, line 115. Change this line :
```js
return currentPos.format() + ' / ' + length.format();
```
with this line :
```js
return currentPos.minutes() + ":" + currentPos.seconds() + "/" + length.minutes() + ":" + length.seconds();
```
since format function appears to not be recognized. I'm not sure this is the best approach, but it works :smiley:

**Comment by Felius** [comment]
> It tooked me few hours to debug this (never done any node before), but I finally managed to make it work!
> There is an error in the display, you can easily find it with `npm run start dev`. The error is in `core/NPOS_DOMBuilder.js`, line 115. Change this line :
> 
> ```js
> return currentPos.format() + ' / ' + length.format();
> ```
> 
> with this line :
> 
> ```js
> return currentPos.minutes() + ":" + (""+currentPos.seconds()).padStart(2,"0") + "/" + length.minutes() + ":" + length.seconds();
> ```
> 
> Also in `node_helper.js`, in line 56, change `isPlaying` by `is_playing`.
> 
> since format function appears to not be recognized. I'm not sure this is the best approach, but it works

Hi!

I receive the following output when I run `npm run start dev`:

> npm ERR! missing script: start
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/pi/.npm/_logs/2020-05-09T11_59_44_865Z-debug.log

The debug log states then states the following:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start', 'dev' ]
> 2 info using npm@6.14.4
> 3 info using node@v14.2.0
> 4 verbose stack Error: missing script: start
> 4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
> 4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
> 4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
> 4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
> 4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
> 4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
> 4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
> 5 verbose cwd /home/pi/magic_mirror/modules/MMM-NowPlayingOnSpotify/authorization
> 6 verbose Linux 4.19.97-v7l+
> 7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start" "dev"
> 8 verbose node v14.2.0
> 9 verbose npm  v6.14.4
> 10 error missing script: start
> 11 verbose exit [ 1, true ]

I'm running MagicMirror² in server only mode in docker and am struggling with getting third party modules to run due to node/npm issues like this. I imagine the core issue might be somewhere else but as a newbie I'm pretty lost with this node/npm stuff and don't quite know where to start.

Help with this or pointers in the right direction would be highly appreciated! :)

**Comment by nunorios** [comment]
@lorettet Worked like a charm.... for someone who never did this you rock.... Thanks a lot

**Comment by sigel** [comment]
@lorettet This worked for me too.

**Comment by Datenzentrale** [comment]
@lorettet This is a dumb question for sure but I can't find the core folder, I think I have everything I need installed since the module worked a few days ago but now it is stuck and I can't locate the folder with the "NPOS_DOMBuilder.js"

**Comment by jam0ra** [comment]
@lorettet this worked for me too, thanks! :)

> Also in `node_helper.js`, in line 56, change `isPlaying` by `is_playing`.

Just to clarify for those still having this issue, it was line 55 for me but I changed it from 
`isPlaying: songInfo.isPlaying,`
to
`is_playing: songInfo.is_playing,`

It then worked perfectly after restarting MM!
