### ISSUE TITLE
problem at step 2 : INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by RIKKO14** [raywo/MMM-NowPlayingOnSpotify#67]
I block in step 2: http: // localhost: 8888 / ...
when I type my Client ID and my Client Secret and authorize my app, it is written: INVALID_CLIENT: Invalid redirect URI
is it possible that this is a problem between my spotify account (which is not premium) and the Dashboard? I tried by creating 2 other app and always the same error.
thanks for your help.

**Comment by RIKKO14** [comment]
I forgot to write http: // localhost: 8888 / callback in Redirect URIs, so I was able to skip this step.
everything went well and I have the spotify logo on my MM, but when I open spotify with my phone and I start a song nothing appears on my MM, I forgot to do something on my phone?

**Comment by Tee6** [comment]
did u write it with the spaces?

**Comment by RIKKO14** [comment]
it's ok.
