### ISSUE TITLE
Log flood when no song playing

### ISSUE THREAD

**Issue by dankarlin** [raywo/MMM-NowPlayingOnSpotify#68]
Works great when Spotify is playing, when no song is playing. With no song playing the following message hits every second or so:

 Whoops! There was an uncaught exception...
0|mm  | [2020-07-01 10:34:49.571] [ERROR]  
0|mm  | TypeError: Cannot read property 'retrieveCurrentlyPlaying' of undefined
0|mm  |     at Class.retrieveCurrentSong (/home/dan/MagicMirror/modules/MMM-NowPlayingOnSpotify/node_helper.js:29:20)
0|mm  |     at Class.socketNotificationReceived (/home/dan/MagicMirror/modules/MMM-NowPlayingOnSpotify/node_helper.js:22:14)
0|mm  |     at Socket.<anonymous> (/home/dan/MagicMirror/js/node_helper.js:113:11)
0|mm  |     at Socket.emit (events.js:198:13)
0|mm  |     at /home/dan/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|mm  |     at process._tickCallback (internal/process/next_tick.js:61:11)
0|mm  | [2020-07-01 10:34:49.572] [LOG]    
0|mm  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [2020-07-01 10:34:49.573] [LOG]    
0|mm  | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm  | [2020-07-01 10:34:50.319] [LOG]

**Comment by arkabase** [comment]
Edit `modules/MMM-NowPlayingOnSpotify/node_helper.js` line 29 : 

```
retrieveCurrentSong: function () {
    this.connector &&
    this.connector.retrieveCurrentlyPlaying()
      .then((response) => {
      ...
```

**Comment by Capt-O** [comment]
confirm this works with no issues so far !

> Edit `modules/MMM-NowPlayingOnSpotify/node_helper.js` line 29 :
> 
> ```
> retrieveCurrentSong: function () {
>     this.connector &&
>     this.connector.retrieveCurrentlyPlaying()
>       .then((response) => {
>       ...
> ```
